### ISSUE TITLE
missing source code files

### ISSUE THREAD

**Issue by stevensrf11** [vmrocha/dryioc.web#1]
I really wish people would post source code that is not missing half a dozen files and actually compiles successfully the first time. There is no Homecontroller.cs file are corresponding view file there is no ServiceController.cs file corresponding whatever file in the API folder. Exactly why is this file in an API folder in the websample

**Comment by vmrocha** [comment]
Hi @stevensrf11, sorry that is an old repository; I don't remember much about it. You are complaining that running the sample application doesn't work out of the box?

**Comment by stevensrf11** [comment]
Not hard to explain.
There is a mvc dryloc sample source and project code available at https://github.com/vmrocha/dryioc.web
the code is missing files.
Do not post sample source projects that are suppose to have all files needed that are missing especially as something as simple as the homecontroller files

**Comment by vmrocha** [comment]
Thank you for the advice! Can you add the missing files for me and submit a pull request?

**Comment by stevensrf11** [comment]
ROFL Who ever created the project need to add the missing the files. How the hell would i know what is in the missing files. ROFL Ask someone to add missing files to a sample project someone else created that took alot brains to ask.

**Comment by vmrocha** [comment]
No problem, I will do my best to not disappoint you anymore with that. Thanks for taking the time to report the problem.

**Comment by stevensrf11** [comment]
why would you ask me to add the file? That does not even make sense.
Never mind I will just recomend use Autofax. 
I was task to look into Dryioc.
LOL I found what I was looking for.

**Comment by vmrocha** [comment]
Maybe you should discuss the usage of DryIoc with the maintainer of the project: https://github.com/dadhi/DryIoc

Have a good day.
